fix: error when trying to save mock request file that doesn't exist
woovibr/apiWithLog pull request #11
Opened 2023-04-26 07:06 UTC by nogw

# Description

As mentioned in issue #10, if the file "mock-requests.json" does not exist and you run the command "WRITE_MOCK=true yarn es scripts/test.ts", an error message will be shown, however, the file is created in any case

# Changes

- Add a simple check inside the try-catch block to determine if the error is due to the file not existing.

# Related Issues

* Closes #10

2023-04-26 12:56 UTC, edumaciel10 commented on src/apiCache.ts
> +    }
I think that this not is the best solution for your problem
Try to find the root cause

2023-04-26 12:56 UTC, edumaciel10 approved these changes

2023-04-26 13:46 UTC, daniloab approved these changes
hi @nogw thanks for the pull request

can you also add an improvement to create the mock JSON file when it does not exist before saving it?

2023-04-26 15:06 UTC, fersilva16 requested changes
Check if the file exists with `fs.existsSync` instead

2023-04-26 15:06 UTC, fersilva16 approved these changes

2023-04-26 23:03 UTC, edumaciel10 requested changes
check the fs opening of writemock

2023-04-27 07:44 UTC, nogw commented
done, using `fs.existsSync` and creating a empty file instead of ignoring the error

2023-04-27 13:06 UTC, fersilva16 approved these changes

2023-04-27 14:28 UTC, edumaciel10 approved these changes
Nice! Good fix

2023-04-27 14:39 UTC, merged